### ISSUE TITLE
Adding options to convert demos into .mp4 and trimming demos for short clips

### ISSUE THREAD

**Issue by dhiganthrao** [skyrim/hlviewer.js#12]
Coming across this repository was like a dream come true. An option to view demos externally without the use of CS? This makes viewing of demos really easy and helpful. However, could a new feature bee added to convert these demos into .mp4 files and trim these demos into short clips of significance, such as examples of a player hacking? Is this even possible? If so, I understand if you're too busy to try to implement these features, but it would be a great help if you did so. 

If it's not a problem, I'd love to work with this repository and understand how it works as well, while trying to implement these features myself (again, if it's possible to do so.) 

Thanks again! This repository will be a huge help for avid CS 1.6 players like me.

**Comment by skyrim** [comment]
Sorry I didn't see this earlier. Too many notifications on GitHub.

It's possible to make what you're asking. I made a simple implementation where it records a 3 second clip in webm format (mp4 is not supported by browsers) that you can save.
skyrim/hlviewer.js@e92cdb1a2f1990dde39c351b89d62eb62d4a0ba6

I don't have time to work on it, so if you want, you can take it from here. I would appreciate it very much.
