### ISSUE TITLE
Autoscan demos

### ISSUE THREAD

**Issue by Traderain** [skyrim/hlviewer.js#2]
Have a folder with demos which is scanned then a list is constructed then its displayed so you can click on it. If you do click on it it checks which map it is on and after that its parsed. Would be much better than the hardcoded demo:mapname list. Also probably instead of referncing the demo/map combo by mapname you should do it with checksum or something so its unique. (These might have been fixed I haven't checked the updates for a while)

**Comment by skyrim** [comment]
Yeah, but you cannot scan folder contents of a server from the browser. You have to implement it on a server using something like PHP, Ruby, node.js... That is out of the scope of this project. Though, I'm planning on making a few example usages of this library and this will be one.

The second thing that you mention is already the way it is implemented now, I think. You just call .load method with the replay file name and when it loads the replay it will then try to load the map for that replay automatically.

**Comment by Traderain** [comment]
Alright
