### ISSUE TITLE
Save the rendered demo as video

### ISSUE THREAD

**Issue by Traderain** [skyrim/hlviewer.js#4]
I think it would be pretty awesome if you could save the rendered video as a gif/mp4. Would be a pretty nice and usefull addition.

**Comment by skyrim** [comment]
Sorry for not responding sooner. I've been busy with my job.

I've been thinking about your suggestion and I don't think browser could handle rendering long, high resolution, high frame rate videos. Maybe just smaller gifs. But, does anyone need that? I tried using ccapture.js and it used over 500MB of memory to render a 5 second clip.

On the other hand if I make an electron app out of this project as you suggested earlier (and I'm planning to whenever I have time), then with access to the users file system it would be feasible to do this.
