### ISSUE TITLE
NEED ANSWERS.

### ISSUE THREAD

**Issue by nofkingideaforname** [skyrim/hlviewer.js#5]
Hello there, this thing could potentially save a lot of time for my projects. I am not experienced here, so if i write bullshit please correct me. My idea is that after a ban on the server player would need to upload demo file to the server where the moderator could watch it and respond quickly to the appeal. For that to happen there should be added the full hud, and a ESP. Is this possible in any way? Any help will be appreciated. If i will see the future with hlviewer customizations i will pay enough to build it for me how i want it to be.

**Comment by skyrim** [comment]
Yes, it's possible. Better send me an email ([skyrim@live.com](mailto:skyrim@live.com)). We can talk about this there.
